package workflow

import "github.com/m-mizutani/leveret/pkg/model"

// IngestResult represents the result of the ingest phase
type IngestResult struct {
	Alert []*IngestedAlert
}

// IngestedAlert represents an alert generated by the ingest phase
type IngestedAlert struct {
	Title       string
	Description string
	Attributes  []*model.Attribute
}

// AgentPrompt represents a prompt for LLM agent execution
type AgentPrompt struct {
	ID      string
	Content string
	Format  string // "text" or "json"
}

// EnrichResult represents the result of the enrich phase (Rego policy evaluation)
type EnrichResult struct {
	Prompt []AgentPrompt
}

// EnrichExecutionResult represents the execution result of a single prompt
type EnrichExecutionResult struct {
	ID     string
	Result string
}

// EnrichExecution represents the execution results of all prompts
type EnrichExecution struct {
	Result []EnrichExecutionResult
}

// TriageResult represents the result of the triage phase
type TriageResult struct {
	Action   string // "accept", "notify", "discard"
	Severity string // "critical", "high", "medium", "low", "info"
	Note     string
}

// WorkflowResult represents the complete workflow result for a single alert
type WorkflowResult struct {
	Alert           *model.Alert
	EnrichResult    *EnrichResult
	EnrichExecution *EnrichExecution
	Triage          *TriageResult
}
